---
- hosts: all
  user: ansible
  become: yes
  gather_facts: no
  tasks:
    - name: install httpd
      action: yum pkg=httpd state=installed
      async: 300
      poll: 10
      notify: restart httpd
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted
