---
- hosts: all
  user: ansible
  gather_facts: yes
  become: yes
  connection: ssh
  tasks:
    name: install nginx
    action: yum name=nginx state=installed
    notify: restart nginx
  Handlers:
    - name: restart nginx
      action: service name=nginx state=restarted