---
- hosts: all
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: add users
      user: name= {{ item }} state=present
      with_items:
        - use1
        - user2

      
 